services:
  enrollment_portal:
    build:
      context: .
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      AWS_PROFILE: ${AWS_PROFILE:-}
    volumes:
      - ./var:/app/var
      - ${HOME:-/root}/.aws:/root/.aws:ro
